### ISSUE TITLE
Handling non-alphanumeric initials in username for anchor_profile()

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna-Redux#3]
We have to handle a case when the first letter of the username is not an alphabetic or numeric symbol. Such as _, #, :, etc.

**Comment by mechanicko** [comment]
@ronin-of-beyonder what would be the allowed format for usernames?

**Comment by tatssato** [comment]
regex will be implemented:
`^[a-zA-Z0-0_](?!.*?[._]{2})[a-zA-Z0-9_.]{2,15}$`
